### ISSUE TITLE
AUTO_BED_MESH and G29 tries to take the probe out first

### ISSUE THREAD

**Issue by almihnea** [kevinakasam/KlackEnder-Probe#1]
The 2 macros mentioned in the title do PROBE_OUT and then PROBE_IN instead of PROBE_IN and afterwards PRORBE_OUT
// 
for the klipper config

**Comment by kevinakasam** [comment]
That's completely correct. First the probe has to get out on the head and than back in into the dock.

**Comment by almihnea** [comment]
Actually I think the probe in and probe out macros have their code switched. The probe in code shouldn't try to move to the left. It should only move to the probe, down and up.
