### ISSUE TITLE
Probe_calibrate not working so well

### ISSUE THREAD

**Issue by ishay320** [kevinakasam/KlackEnder-Probe#12]
i used this macro:
```
[gcode_macro calibrate_nozzle]
gcode:
  G28
  PROBE_OUT
  G0 X117 Y117 # the center of print bed
  Probe_calibrate
  PROBE_IN
```

it does good on `G28` and on `probe_out`, when it get to probe calibrate it starts good but when it returns the probe it move to x0 y-8.
there is a reasen to move it to 0 0 on `probe_in`?

**Comment by ishay320** [comment]
the fix that i have got is:
```
[gcode_macro calibrate_nozzle]
gcode:
  G28
  PROBE_OUT
  G0 X117 Y117 # the center of print bed
  Probe_calibrate
```
and removing the probe manually

**Comment by kevinakasam** [comment]
> there is a reasen to move it to 0 0 on probe_in?

Yes because after the probe got stored the print may start and starting at the zero position might help with other macros you use for a purgeline or so
