### ISSUE TITLE
bed mesh macro

### ISSUE THREAD

**Issue by ishay320** [kevinakasam/KlackEnder-Probe#13]
better macro for bed mesh:
```
[gcode_macro BED_MESH_CALIBRATE]
rename_existing: _BED_MESH_CALIBRATE
description: Perform Mesh Bed Leveling with klicky automount
gcode:
	G90
    PROBE_OUT

    _BED_MESH_CALIBRATE {% for p in params
           %}{'%s=%s ' % (p, params[p])}{%
          endfor %}

    PROBE_IN
```

it works with the original bed mesh button

**Comment by DasBurninator** [comment]
Its not just the bed mesh macro that has this issue that could be easily resolved. It is all of the macros. z_tilt has this issue as well.

I suggest using the klickyprobe macros instead. Much better written.

**Comment by kevinakasam** [comment]
Thanks for the comment! Yes you're right renaming the existing macros makes the usage a little easier. I will give your macro a try when I'm back home and edit the Klackender.cfg.

**Comment by oldcrazyeye** [comment]
No progress in this thread, closing
