### ISSUE TITLE
Ender 5 support?

### ISSUE THREAD

**Issue by qwertychouskie** [kevinakasam/KlackEnder-Probe#21]
At the lab, we have an Ender 3, and Ender 3 Pro, and an Ender 5 Pro.  Would be nice to be able to use this on all 3 printers :)

I imagine the part that goes on the toolhead would be identical, but the part that mounts to the frame would be a bit different, and probably the load/upload sequences would have to be tweaked too.

**Comment by oldcrazyeye** [comment]
Nothing in the works for ender 5 currently. Files are parametric so feel free to give it a shot in cad.
