### ISSUE TITLE
Please help Klackender Config issue

### ISSUE THREAD

**Issue by iiiiiiiiddddddkkkkkkk** [kevinakasam/KlackEnder-Probe#24]
I just set up the klackender config and i got this error from klipper any suggestions?

Section 'menu __main' is not a valid config section

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by YungChin95** [comment]
Remove the bottom part of the config named "Klackender Menu"

**Comment by iiiiiiiiddddddkkkkkkk** [comment]
ok i'll try that thanks for the rapid response

**Comment by iiiiiiiiddddddkkkkkkk** [comment]
did that now i get this 

Option 'points' is not valid in section 'homing_override'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by iiiiiiiiddddddkkkkkkk** [comment]
> Remove the bottom part of the config named "Klackender Menu"

I did that now I get this error

Option 'points' is not valid in section 'homing_override'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by iiiiiiiiddddddkkkkkkk** [comment]
never mind i forgot to comment out the stuff in z tilt
