### ISSUE TITLE
"Probe triggered prior to movement" error randomly popped up when running AUTO_BED_MESH

### ISSUE THREAD

**Issue by AhambaliJ** [kevinakasam/KlackEnder-Probe#28]
Hi all,

I'm making this issue to share my experience troubleshooting error mentioned and the solution, in case anyone is experiencing the same issue.
Just managed to installed the parts and get the probe to smoothly goes in and out of its dock.
Absolutely no problem when homing Z.
Tested manually attaching probe to trigger the probe on bed, and raising the head(Z) +1 at a time, probe gets open at sometimes at +1, other times at +3. I.e ranging from Z 0 to Z 3
This causes issues during calibrating bed mesh, specifically when taking multiple sample as the probe get stuck in "Triggered" status and which give me a clue that it needs to move upwards(+Z) more.

Solution:
Go into printer.cfg and scroll down to the [probe] section. Increase the value of "sample_retract_dist".
For me, I made the value as the same as my "z_offset" value.

Hope this helps someone.

**Comment by kevinakasam** [comment]
Thanks for sharing :)
