### ISSUE TITLE
Automatic Z Calibration

### ISSUE THREAD

**Issue by genericapplesauce** [kevinakasam/KlackEnder-Probe#3]
What would it take to get Automatic Z Calibration on an Ender 3? i.e. https://github.com/protoloft/klipper_z_calibration

The Vorons have a trigger they push with the nozzle, I'm assuming that won't work without modifying the Ender's left gantry bracket hitting the z stop?

Big fan of your work, Thanks!

**Comment by kevinakasam** [comment]
Wanna use this comment to say that this in the making and runs as Beta on my Discord :)
