### ISSUE TITLE
Wiring an Ender3 S1 Pro issue

### ISSUE THREAD

**Issue by icemul1900** [kevinakasam/KlackEnder-Probe#30]
I'm trying to wire the micro switch to the Ender3 S1 Pro and I'm not having any luck. I have been trying the "Z Limit Interface" but it's 3 prongs, so I've tried all the combos but none of them work. 
How am I supposed to wire the Klack to the S1 Pro motherboard?  

![CREALITY-3D-Ender-3-S1-Ender3-S1-PRO-Silent-Motherboard-32-Bit-TMC2208-Mainboard-Silent-Printing jpg_80x80](https://github.com/kevinakasam/KlackEnder-Probe/assets/97625270/4a5c1ecf-ff27-4a2b-9627-e74ceec99ae9)

**Comment by oldcrazyeye** [comment]
You should absolutely be able to use the z limit pins. Only use IO and GND and not 5v. Identify the pin mapping of the IO pin and add that to klipper config under `probe_pin`
