### ISSUE TITLE
Chamfer of 0.4mm not used on bottom edge of parts

### ISSUE THREAD

**Issue by DasBurninator** [kevinakasam/KlackEnder-Probe#7]
Fillets are used on some parts, other parts don't have anything at all.

Chamfer @ 45º on the bottom edges of parts give enough room to prevent elephants footing. Fillets shouldn't be used due to them having too much overhang making the 2nd layer look very sloppy. Especially with plastics like ABS.

Example of how they parts should look:
![image](https://user-images.githubusercontent.com/41883401/210301730-785a3a8d-0b11-4061-b41c-0462bc43ae63.png)

You can see the difference in how they lay down in the slicer too. Fillet on the left, Chamfer on the right.
Much less gap fill used in the slicer on these smaller parts. Might be harder to see, but the overhang difference can be seen here too.
![image](https://user-images.githubusercontent.com/41883401/210302694-b4fbbed6-7ed5-49b5-994c-fc1da9acb3be.png)

**Comment by sleyshaw24** [comment]
I agree with this. When I modified the parametric files to fit my volcano setup, I also used 0.4mm chamfers instead.
