### ISSUE TITLE
Probe mount doesn't fit to Ender 3S1

### ISSUE THREAD

**Issue by neshami** [kevinakasam/KlackEnder-Probe#9]
Probe mount from STL folder doesn’t fit to Ender 3S1. Horizontal opening on probe mount which is included is 17.1mm and tab on 3S1 carriage is 19.6 mm wide and 3mm in height. 
Can You include mount for Ender 3S1 to measures and include in 3S1 folder?

**Comment by neshami** [comment]
Can You add that file HarryPulvirenti uploaded last for probe mount for 3S1? That file solved problem.

**Comment by AustinTylerDean** [comment]
I would like whatever Harry made as well. I have to grind down the side, and after a few months I'm having problems with open circuits due to the slop in the probe mount.
